server:
  port: 30000
spring:
  redis:
    host: 192.168.95.20
    port: 6379
  application:
    name: cache




eureka:
  client:
    service-url:
      defaultZone: http://test:test@localhost:20000/eureka
